CREATE DATABASE typescript_MySQL;

CREATE TABLE posts(
  id INT(11) NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  createda_at TIMESTAMP CURRENT_TIMESTAMP
);

DESCRIBE posts;